
visualization:
  plot_title: "Count of Pokemon Species per Color"
  x_axis_title: "Color"
  y_axis_title: "Count"
  figure_size:
    width: 10
    height: 12

output:
  save_path: "output/"
  log_path: "output/"
  

